name: ComposeStarter

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  SAMPLE_PATH: ComposeStarter

jobs:
  apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Make gradlew executable
        run: chmod +x ${{ env.SAMPLE_PATH }}/gradlew

      - name: Build debug APK
        working-directory: ${{ env.SAMPLE_PATH }}
        run: ./gradlew app:assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: wear-apk
          path: ${{ env.SAMPLE_PATH }}/app/build/outputs/apk/debug/*.apk
